### ISSUE TITLE
Entendiendo un poco

### ISSUE THREAD

**Issue by Ceboc** [windie-rozureido/ProyectoTemasSelectosFisComp2016-1#2]
En principio ya entendí lo que está pasando,

Resumen:
La función modulo2pi:
- Acepta dos posiciones y devuelve su diferencia en un módulo 2 pi, que es lo que queremos pues sólo nos interesa la posición entre 2 coches consecutivos.

La función fSec:
-De argumentos reales, acepta un periodo, dos series de Taylor para cada coche y longitud del coche de enfrente, con eso construye los coeficientes mediente recusión de la función que en principio se va a integrar,

La función fmax:
-Sólo requiere de argumento la velocidad máxima permitida, con lo que construye la serie de Taylor, a "primer orden" (aunque realmente la operaremos a orden 10 con los demás coeficientes cero) pues ya no requeriremos aceleración en este caso.

La función stepsize:
-Nos devuelve el tamaño del paso necesario en t, Me habían sugerido que usara un arreglo de coeficientes y eligiera de ahí el coeficiente de mayor orden distinto de cero y seguir..., pero como veo que funciona esta implementación, creo que está bien.

La función speed:
-Dado un arreglo de posiciones iniciales, de longitudes (así las pienso), de periodos y velocidades, genera un arreglo de las funciones de velocidad que se van a aplicar a cada coche. Le estuve moviendo hasta entender bien lo que estaba haciendo ese código. Lo bueno es que esta parte ya es completamente escalable a lo que vamos a emplear al final.

Lo que ya no entendí.

En la función de prueba que haces, en la función series, usas una línea
velocidad_sec(T2,x2,x1,L1).coeffs[i-1]/i

por construcción lo que se está haciendo en ese punto es evaluar la función fSec, y sacar los coeficientes de las posiciones, es decir este debe ser el momento en el que enserio estamos haciendo la integración, al menos de momento analítica, pues falta ingresar el valor del tiempo. 
Ahora, no veo cómo haces fSec, velocidad_sec, o quién rayos es velocidad_sec en todo caso. Eso no me queda claro. 

Lo que sigue por otra parte es cómo implementar esta parte del código para tantos coches querramos, yo creo que la función speed está bien como está. Estaba pensando es hacer una macros para hacer toda esta familia de comparaciones, Pero para eso necesito entender del todo que estás haciendo en la parte de Series, sobre todo por esa función que te digo.

**Comment by windie-rozureido** [comment]
La función 'series' Calcula las series de los coches cuando sólo se tienen dos coches. velocidad_sec es lo mismo que fSec. Cambió el nombre por alguna extraña razón. Ajá, sigue implementar algo parecido a 'series' pero para n carros.

Mañana le daré con todo. Ya terminé todo lo demás.

**Comment by Ceboc** [comment]
Yo aún tengo examen y debo entregar un reporte pero también le meteré mano

**Comment by windie-rozureido** [comment]
Ok, Yo estoy trabajando en una función que generará las series de todos los coches. Para después evaluar y conocer la siguiente condición inicial.

**Comment by windie-rozureido** [comment]
Ya se tiene esa función. He actualizado el repositorio con ese agregado. Falta echar a andar el método de taylor.

**Comment by Ceboc** [comment]
Deja eso yo lo hago.

**Comment by Ceboc** [comment]
Ya subí algunos avances a mi git, ya casi está lo tendré corriendo después
de la hora de comer

**Comment by windie-rozureido** [comment]
Ya lo vi, se ve bien. Sólo que en la última función que defines, donde ya se implementa el método de taylor, no cambias las condiciones iniciales. Siempre son las mismas.

**Comment by Ceboc** [comment]
Pero la serie se aproxima en rededor de la última posición por eso
requerimos actualizar las condiciones iniciales. Ya lo corrí para que me
devolviera los tiempos y corre bien por lo que supongo que lo demás lo hace
bien sólo que ahora estoy viendo cómo sacar los valores de una forma útil.

**Comment by Ceboc** [comment]
Voy a revisar una tarea del año pasado pues ese problema ya se me había
presentado. Subo ahorita mis cambios.

**Comment by windie-rozureido** [comment]
Tal vez no tengo la versión actualizada, pero no veo que cambie la condición inicial. Cualquier cosa a
quí estaré.

**Comment by Ceboc** [comment]
Me refería a la actualización de velocidades y posiciones no se esta
dejando, no logró sacar los datos hay un problema desde la declaración de
los arreglos . si le digo que saque la evolución de velocidades y
posiciones que no logro sacar a la vez, se observa que hay algo raro en el
comportamiento.

**Comment by Ceboc** [comment]
Ahora te mando un forkeo.

**Comment by windie-rozureido** [comment]
El vector de velocidades nunca cambia. Es como un límite de velocidad de seguridad.

**Comment by windie-rozureido** [comment]
Y también hay que hacer una función, parecida a módulo2pi. Que cuando la posición pase de $2\pi$ lo escriba módulo "2\pi"

**Comment by windie-rozureido** [comment]
Otra cosa. No sé como hacer el merge XD

**Comment by Ceboc** [comment]
Revisa en mi git lo que está pasando en el branch cesar.

**Comment by windie-rozureido** [comment]
Sí, ahí estoy viendo. Por eso te digo que no debes cambiar el vector de velocidades.

**Comment by Ceboc** [comment]
Ya lo moví y avanza normal pero las posiciones se pasan de 350 grados,
ahora lo subo

**Comment by Ceboc** [comment]
Lo acabó de subir

**Comment by windie-rozureido** [comment]
Es normal que salga de 2pi. Hay que hacer una evaluación a cada posición que sale. Si resulta ser mayor que 2pi,  escribirlo en su ángulo módulo 2pi.

**Comment by windie-rozureido** [comment]
Yo lo haría en la función positions. Justo antes del Push!(). un If Pos > 2pi, Pos = Pos - 2pi.

**Comment by Ceboc** [comment]
Ya salieron los datos como los vamos a necesitar, ahorita los subo,
perdidos entre todo ese montón de advertencias esta el arreglo que se va a
graficar.

**Comment by Ceboc** [comment]
¿Como lo vez?

**Comment by windie-rozureido** [comment]
Sí parecen buenos datos.
Falta poner las distancias en módulo 2pi

**Comment by Ceboc** [comment]
Ya lo hice, escribí una función que pasa las posiciones a módulo 2 pi, pero
ya a la salida de datos no quería interferir con la evaluación de
distancias que tu habías hecho.

**Comment by windie-rozureido** [comment]
Creo que no afecta.

**Comment by windie-rozureido** [comment]
o ¿Si afectó?

**Comment by Ceboc** [comment]
El problema que ahora veo es en el tamaño del paso pues avanza mucho, y no
nos va a dejar ver un movimiento suave.

**Comment by windie-rozureido** [comment]
Y y se hace la épsilon más pequeña?

**Comment by Ceboc** [comment]
No no afectó, pero para verificar que todo va como lo esperado hay que
animar. ¿No sabes como hacer para que no salgan tantas advertencias?

**Comment by Ceboc** [comment]
Pues lo estoy evaluando y creó que mate a mi máquina le di 2.0e-20

**Comment by windie-rozureido** [comment]
Mmm no, no sé. De hecho no conocía ese paquete para graficar.

No sé animar :c

**Comment by Ceboc** [comment]
Si la maté.

**Comment by windie-rozureido** [comment]
Jajaja

**Comment by Ceboc** [comment]
Tengo un problema con las animaciones, por que quise animar cosas que ya
tenía hace un año y no corrieron y los manuales creo que no están lo
suficientemente actualizados.

**Comment by Ceboc** [comment]
Deja lo subo y lo revizas, y le mueves la epsilon

**Comment by windie-rozureido** [comment]
Sí. Pero antes iré a buscar algo de cenar. Después intentaré graficar también. Intentaré usar Pyplot.
